name: Implementation Testing

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  foundation:

    strategy:
      matrix:
        python-version: ["3.10"]
    defaults:
      run:
        shell: bash -l {0}
    name: linux-64-py${{ matrix.python-version }}
    runs-on: ubuntu-latest
    steps:
      # checkout the code in this repository
      - uses: actions/checkout@v4
        with:
          path: 'arc-activitysim'

      # checkout the main branch of ActivitySim itself
      - uses: actions/checkout@v4
        with:
          repository: 'ActivitySim/activitysim'
          ref: main
          path: 'activitysim'
          fetch-depth: 0  # get all tags, lets setuptools_scm do its thing

      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
            miniforge-version: latest
            activate-environment: asim-test
            python-version: ${{ matrix.python-version }}

      - name: Set cache date for year and month
        run: echo "DATE=$(date +'%Y%m')" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          path: ~/conda_pkgs_dir
          key: linux-64-conda-${{ hashFiles('activitysim/conda-environments/github-actions-tests.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: Update environment
        run: |
          conda env update -n asim-test -f activitysim/conda-environments/github-actions-tests.yml

      - name: Install activitysim
        # installing without dependencies is faster, we trust that all needed dependencies
        # are in the conda environment defined above.  Also, this avoids pip getting
        # confused and reinstalling tables (pytables).
        run: |
          python -m pip install ./activitysim --no-deps

      - name: Conda checkup
        run: |
          conda info -a
          conda list

      - name: Get the Fulton data
        run: |
          cd arc-activitysim
          python scripts/fetch-fulton.py

      - name: Run progressive tests
        run: |
          python -m pytest arc-activitysim/tests/test_fulton.py

      - name: Run without Sharrow
        run: |
          cd arc-activitysim
          python scripts/run-fulton.py
          
      - name: Upload legacy artifacts
        uses: actions/upload-artifact@v4
        with:
          name: legacy-outputs
          path: |
            ${{ github.workspace }}/arc-activitysim/output-fulton-legacy/final_*.csv
            ${{ github.workspace }}/arc-activitysim/output-fulton-legacy/*.log
            ${{ github.workspace }}/arc-activitysim/output-fulton-legacy/timing_log.csv

      - name: Check legacy outputs
        run: |
          cd arc-activitysim
          python scripts/check-fulton.py --check-dir ${{ github.workspace }}/arc-activitysim/output-fulton-legacy

      - name: Run with Sharrow
        run: |
          cd arc-activitysim
          python scripts/run-fulton.py --sharrow

      - name: Upload Sharrow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sharrow-outputs
          path: |
            ${{ github.workspace }}/arc-activitysim/output-fulton-sharrow/final_*.csv
            ${{ github.workspace }}/arc-activitysim/output-fulton-sharrow/*.log
            ${{ github.workspace }}/arc-activitysim/output-fulton-sharrow/timing_log.csv

      - name: Check sharrow outputs
        run: |
          cd arc-activitysim
          python scripts/check-fulton.py --check-dir ${{ github.workspace }}/arc-activitysim/output-fulton-sharrow

